<?php
$ingredients = [
    [
        'ActorName' => 'Animal_Insect_S',
        'EuenName' => 'Hightail Lizard',
        'Classification' => NULL,
        'BuyingPrice' => 10,
        'SellingPrice' => 2,
        'Color' => 'Brown',
        'AdditionalDamage' => 'Impossible',
        'EffectLevel' => 1,
        'EffectType' => 'AllSpeed',
        'EffectiveTime' => 900,
    ],
    [
        'ActorName' => 'Animal_Insect_S',
        'EuenName' => 'Cold Darner',
        'Classification' => NULL,
        'BuyingPrice' => 10,
        'SellingPrice' => 2,
        'Color' => 'Blue',
        'AdditionalDamage' => 'Impossible',
        'EffectLevel' => 2,
        'EffectType' => 'ResistHeat',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Animal_Insect_T',
        'EuenName' => 'Warm Darner',
        'Classification' => NULL,
        'BuyingPrice' => 10,
        'SellingPrice' => 2,
        'Color' => 'Red',
        'AdditionalDamage' => 'Impossible',
        'EffectLevel' => 2,
        'EffectType' => 'ResistCold',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Animal_Insect_X',
        'EuenName' => 'Fireproof Lizard',
        'Classification' => NULL,
        'BuyingPrice' => 25,
        'SellingPrice' => 5,
        'Color' => 'Gray',
        'AdditionalDamage' => 'Impossible',
        'EffectLevel' => 1,
        'EffectType' => 'ResistBurn',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'BeeHome',
        'EuenName' => 'Courser Bee Honey',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'StaminaRecover',
        'EffectiveTime' => 0,
        'HitPointRecover' => 8
    ],
    [
        'ActorName' => 'ElectricalFruit',
        'EuenName' => 'Shock Fruit',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'AttackUpThunderstorm',
        'EffectiveTime' => 900,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'FireFruit',
        'EuenName' => 'Fire Fruit',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Red',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'AttackUpHot',
        'EffectiveTime' => 900,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'IceFruit',
        'EuenName' => 'Ice Fruit',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'White',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'AttackUpCold',
        'EffectiveTime' => 900,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'Item_FishGet_A',
        'EuenName' => 'Hyrule Bass',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_FishGet_AA',
        'EuenName' => 'Ancient Arowana',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_FishGet_AC',
        'EuenName' => 'Glowing Cave Fish',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 'LightEmission',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_B',
        'EuenName' => 'Hearty Bass',
        'Classification' => NULL,
        'BuyingPrice' => 72,
        'SellingPrice' => 18,
        'Color' => NULL,
        'AdditionalDamage' => 8,
        'EffectLevel' => 'LifeMaxUp',
        'EffectType' => 0,
        'EffectiveTime' => 8,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_C',
        'EuenName' => 'Chillfin Trout',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => 3,
        'EffectLevel' => 'ResistHot',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_D',
        'EuenName' => 'Voltfin Trout',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => 3,
        'EffectLevel' => 'ResistElectric',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_E',
        'EuenName' => 'Mighty Carp',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 'AttackUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_F',
        'EuenName' => 'Mighty Porgy',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => NULL,
        'AdditionalDamage' => 3,
        'EffectLevel' => 'AttackUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_G',
        'EuenName' => 'Armored Porgy',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => NULL,
        'AdditionalDamage' => 3,
        'EffectLevel' => 'DefenseUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_H',
        'EuenName' => 'Armored Carp',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 'DefenseUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_H',
        'EuenName' => 'Armored Carp',
        'Classification' => NULL,
        'BuyingPrice' => 120,
        'SellingPrice' => 30,
        'Color' => NULL,
        'AdditionalDamage' => 10,
        'EffectLevel' => 'None',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_I',
        'EuenName' => 'Hearty Salmon',
        'Classification' => NULL,
        'BuyingPrice' => 80,
        'SellingPrice' => 20,
        'Color' => NULL,
        'AdditionalDamage' => 16,
        'EffectLevel' => 'LifeMaxUp',
        'EffectType' => 0,
        'EffectiveTime' => 16,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_J',
        'EuenName' => 'Sizzlefin Trout',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => 3,
        'EffectLevel' => 'ResistCold',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_L',
        'EuenName' => 'Staminoka Bass',
        'Classification' => NULL,
        'BuyingPrice' => 72,
        'SellingPrice' => 18,
        'Color' => NULL,
        'AdditionalDamage' => 4,
        'EffectLevel' => 'StaminaRecover',
        'EffectType' => 0,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_M',
        'EuenName' => 'Sneaky River Snail',
        'Classification' => NULL,
        'BuyingPrice' => 24,
        'SellingPrice' => 6,
        'Color' => NULL,
        'AdditionalDamage' => 1,
        'EffectLevel' => 'QuietnessUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_X',
        'EuenName' => 'Stealthfin Trout',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 'QuietnessUp',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_FishGet_Z',
        'EuenName' => 'Sanke Carp',
        'Classification' => NULL,
        'BuyingPrice' => 80,
        'SellingPrice' => 20,
        'Color' => NULL,
        'AdditionalDamage' => 0,
        'EffectLevel' => 'None',
        'EffectType' => 900,
        'EffectiveTime' => 4,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Fruit_A',
        'EuenName' => 'Apple',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Red',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_B',
        'EuenName' => 'Wildberry',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Pink',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_C',
        'EuenName' => 'Voltfruit',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistElectric',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_E',
        'EuenName' => 'Fleet-Lotus Seeds',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'AllSpeed',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_F',
        'EuenName' => 'Hydromelon',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistHot',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_G',
        'EuenName' => 'Palm Fruit',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Fruit_H',
        'EuenName' => 'Mighty Bananas',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'AttackUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_I',
        'EuenName' => 'Spicy Pepper',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Red',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistCold',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_J',
        'EuenName' => 'Fortified Pumpkin',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'DefenseUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_K',
        'EuenName' => 'Acorn',
        'Classification' => NULL,
        'BuyingPrice' => 8,
        'SellingPrice' => 2,
        'Color' => 'Brown',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'Item_Fruit_L',
        'EuenName' => 'Chickaloo Tree Nut',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Crimson',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'Item_Fruit_M',
        'EuenName' => 'Hylian Tomato',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Fruit_N',
        'EuenName' => 'Sun Pumpkin',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 4,
        'EffectType' => 'LifeRepair',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Fruit_P',
        'EuenName' => 'Golden Apple',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 6
    ],
    [
        'ActorName' => 'Item_InsectGet_K',
        'EuenName' => 'Razorclaw Crab',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 2,
        'EffectType' => 'AttackUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_InsectGet_O',
        'EuenName' => 'Ironshell Crab',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 2,
        'EffectType' => 'DefenseUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_InsectGet_Z',
        'EuenName' => 'Bright-Eyed Crab',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => NULL,
        'AdditionalDamage' => 2,
        'EffectLevel' => 2,
        'EffectType' => 'StaminaRecover',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Material_01',
        'EuenName' => 'Cane Sugar',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_02',
        'EuenName' => 'Goron Spice',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Crimson',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_03',
        'EuenName' => 'Hylian Rice',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'White',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Material_04',
        'EuenName' => 'Bird Egg',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Material_05',
        'EuenName' => 'Fresh Milk',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'White',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Material_06',
        'EuenName' => 'Goat Butter',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_07',
        'EuenName' => 'Tabantha Wheat',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
    ],
    [
        'ActorName' => 'Item_Material_07',
        'EuenName' => 'Hightail Lizard',
        'Classification' => NULL,
        'BuyingPrice' => 10,
        'SellingPrice' => 2,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'IncreaseMovementSpeed',
        'EffectiveTime' => 150,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_08',
        'EuenName' => 'Monster Extract',
        'Classification' => NULL,
        'BuyingPrice' => 50,
        'SellingPrice' => 12,
        'Color' => 'Purple',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_09',
        'EuenName' => 'Oil Jar',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Material_10',
        'EuenName' => 'Hateno Cheese',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Material_11',
        'EuenName' => 'Dark Clump',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Purple',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'MiasmaGuard',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_Meat_01',
        'EuenName' => 'Raw Meat',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => NULL,
        'AdditionalDamage' => 0,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Meat_02',
        'EuenName' => 'Raw Prime Meat',
        'Classification' => NULL,
        'BuyingPrice' => 60,
        'SellingPrice' => 15,
        'Color' => NULL,
        'AdditionalDamage' => 0,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 6
    ],
    [
        'ActorName' => 'Item_Meat_06',
        'EuenName' => 'Raw Bird Drumstick',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => NULL,
        'AdditionalDamage' => 1,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Meat_07',
        'EuenName' => 'Raw Bird Thigh',
        'Classification' => NULL,
        'BuyingPrice' => 60,
        'SellingPrice' => 15,
        'Color' => NULL,
        'AdditionalDamage' => 1,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 6
    ],
    [
        'ActorName' => 'Item_Meat_11',
        'EuenName' => 'Raw Gourmet Meat',
        'Classification' => NULL,
        'BuyingPrice' => 140,
        'SellingPrice' => 35,
        'Color' => NULL,
        'AdditionalDamage' => 0,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 12
    ],
    [
        'ActorName' => 'Item_Meat_12',
        'EuenName' => 'Raw Whole Bird',
        'Classification' => NULL,
        'BuyingPrice' => 140,
        'SellingPrice' => 35,
        'Color' => NULL,
        'AdditionalDamage' => 1,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 12
    ],
    [
        'ActorName' => 'Item_Mushroom_A',
        'EuenName' => 'Stamella Shroom',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'StaminaRecover',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_B',
        'EuenName' => 'Chillshroom',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Blue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'ResistHot',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_C',
        'EuenName' => 'Sunshroom',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Red',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'ResistCold',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_E',
        'EuenName' => 'Hylian Shroom',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Red',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_F',
        'EuenName' => 'Hearty Truffle',
        'Classification' => NULL,
        'BuyingPrice' => 80,
        'SellingPrice' => 20,
        'Color' => 'Black',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 4,
        'EffectType' => 'LifeMaxUp',
        'EffectiveTime' => 0,
        'HitPointRecover' => 8
    ],
    [
        'ActorName' => 'Item_Mushroom_H',
        'EuenName' => 'Zapshroom',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'ResistElectric',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_J',
        'EuenName' => 'Silent Shroom',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightBlue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'QuietnessUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_L',
        'EuenName' => 'Razorshroom',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Crimson',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'AttackUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_M',
        'EuenName' => 'Ironshroom',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Brown',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'DefenseUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_Mushroom_N',
        'EuenName' => 'Big Hearty Truffle',
        'Classification' => NULL,
        'BuyingPrice' => 100,
        'SellingPrice' => 25,
        'Color' => 'Black',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 16,
        'EffectType' => 'LifeMaxUp',
        'EffectiveTime' => 0,
        'HitPointRecover' => 12
    ],
    [
        'ActorName' => 'Item_Mushroom_O',
        'EuenName' => 'Endura Shroom',
        'Classification' => NULL,
        'BuyingPrice' => 60,
        'SellingPrice' => 15,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ExStaminaMaxUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_Mushroom_P',
        'EuenName' => 'Skyshroom',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightBlue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'Item_MushroomGet_D',
        'EuenName' => 'Rushroom',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Purple',
        'AdditionalDamage' => 1,
        'EffectLevel' => 1,
        'EffectType' => 'AllSpeed',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_MushroomGet_K',
        'EuenName' => 'Brightcap',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'LightEmission',
        'EffectiveTime' => 900,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_PlantGet_A',
        'EuenName' => 'Hyrule Herb',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_PlantGet_B',
        'EuenName' => 'Hearty Radish',
        'Classification' => NULL,
        'BuyingPrice' => 80,
        'SellingPrice' => 20,
        'Color' => 'Pink',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 12,
        'EffectType' => 'LifeMaxUp',
        'EffectiveTime' => 0,
        'HitPointRecover' => 10
    ],
    [
        'ActorName' => 'Item_PlantGet_C',
        'EuenName' => 'Big Hearty Radish',
        'Classification' => NULL,
        'BuyingPrice' => 100,
        'SellingPrice' => 25,
        'Color' => 'Pink',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 20,
        'EffectType' => 'LifeMaxUp',
        'EffectiveTime' => 0,
        'HitPointRecover' => 16
    ],
    [
        'ActorName' => 'Item_PlantGet_E',
        'EuenName' => 'Cool Safflina',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightBlue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistHot',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_F',
        'EuenName' => 'Warm Safflina',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistCold',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_G',
        'EuenName' => 'Mighty Thistle',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'AttackUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_H',
        'EuenName' => 'Armoranth',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Purple',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'DefenseUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_I',
        'EuenName' => 'Blue Nightshade',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Blue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'QuietnessUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_J',
        'EuenName' => 'Silent Princess',
        'Classification' => NULL,
        'BuyingPrice' => 30,
        'SellingPrice' => 10,
        'Color' => 'White',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 3,
        'EffectType' => 'QuietnessUp',
        'EffectiveTime' => 1200,
        'HitPointRecover' => 4
    ],
    [
        'ActorName' => 'Item_PlantGet_L',
        'EuenName' => 'Electric Safflina',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'ResistElectric',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_M',
        'EuenName' => 'Swift Carrot',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'Orange',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'AllSpeed',
        'EffectiveTime' => 300,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_PlantGet_O',
        'EuenName' => 'Swift Violet',
        'Classification' => NULL,
        'BuyingPrice' => 40,
        'SellingPrice' => 10,
        'Color' => 'Purple',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 2,
        'EffectType' => 'AllSpeed',
        'EffectiveTime' => 900,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_Q',
        'EuenName' => 'Endura Carrot',
        'Classification' => NULL,
        'BuyingPrice' => 80,
        'SellingPrice' => 20,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 4,
        'EffectType' => 'ExStaminaMaxUp',
        'EffectiveTime' => 300,
        'HitPointRecover' => 8
    ],
    [
        'ActorName' => 'Item_PlantGet_R',
        'EuenName' => 'Sundelion',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 12,
        'EffectType' => 'LifeRepair',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'Item_PlantGet_S',
        'EuenName' => 'Stambulb',
        'Classification' => NULL,
        'BuyingPrice' => 16,
        'SellingPrice' => 4,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'StaminaRecover',
        'EffectiveTime' => 0,
        'HitPointRecover' => 2
    ],
    [
        'ActorName' => 'Item_PlantGet_U',
        'EuenName' => 'Korok Frond',
        'Classification' => NULL,
        'BuyingPrice' => 12,
        'SellingPrice' => 3,
        'Color' => 'Green',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'LightBall_Large',
        'EuenName' => 'Giant Brightbloom Seed',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'LightBall_Small',
        'EuenName' => 'Brightbloom Seed',
        'Classification' => NULL,
        'BuyingPrice' => 32,
        'SellingPrice' => 8,
        'Color' => 'LightYellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 0,
        'EffectType' => 'None',
        'EffectiveTime' => 0,
        'HitPointRecover' => 0
    ],
    [
        'ActorName' => 'LightFruit',
        'EuenName' => 'Dazzlefruit',
        'Classification' => NULL,
        'BuyingPrice' => 20,
        'SellingPrice' => 5,
        'Color' => 'Yellow',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'None',
        'EffectiveTime' => 900,
        'HitPointRecover' => 1
    ],
    [
        'ActorName' => 'WaterFruit',
        'EuenName' => 'Splash Fruit',
        'Classification' => NULL,
        'BuyingPrice' => 10,
        'SellingPrice' => 2,
        'Color' => 'LightBlue',
        'AdditionalDamage' => NULL,
        'EffectLevel' => 1,
        'EffectType' => 'SwimSpeedUp',
        'EffectiveTime' => 900,
        'HitPointRecover' => 1
    ]
];